Repository paketo-buildpacks/native-image, pull requests merged in 2021-11, with the labels that each got.

#117 Added buildpack.toml entries for SBOM formats, bumped API & libpak
  buildpack.toml
  go.mod
  go.sum
Labels: semver:minor, type:dependency-upgrade

#113 Do not require Start-Class in MANIFEST.MF
  native/build.go
  native/native_image.go
  native/native_image_test.go
Labels: semver:patch, type:bug

#119 Added support to create launch sbom
  native/build.go
  native/build_test.go
Labels: semver:minor, type:enhancement
